version: '3'

services:
  # mysql:
  #   image: mysql:5.7
  #   restart: always
  #   command: --default-authentication-plugin=mysql_native_password
  #   platform: linux/x86_64
  #   environment:
  #     MYSQL_DATABASE: 'db'
  #     # So you don't have to use root, but you can if you like
  #     MYSQL_USER: 'root'
  #     # You can use whatever password you like
  #     MYSQL_PASSWORD: 'password'
  #     # Password for root access
  #     MYSQL_ROOT_PASSWORD: 'password'
  #   ports:
  #     # <Port exposed> : < MySQL Port running inside container>
  #     - '3306:3306'
  #   expose:
  #     # Opens port 3306 on the container
  #     - '3306'
  #     # Where our data will be persisted
  #   volumes:
  #     - my-db:/var/lib/mysql
  #   networks:
  #     - vcx_network
  #   container_name: mysqldb
  wallet-app:
    platform: linux/x86_64
    restart: unless-stopped
    container_name: vcx-cloud-wallet
    hostname: wallet-app
    restart: always
    build:
      context: .
    volumes: 
      - ./data:/root/data
      - ./web:/root/web
      - ./server:/root/server
    ports:
      - "8081:80"
      - "3000:3000"
    env_file:
      - ./config/env-cloud-wallet.dev
    # depends_on:
      # - mysql
    networks:
      - vcx_network
networks:
  vcx_network:
volumes:
  server:
  my-db:
