version: '3'

services:
  # db:
  #   image: mysql:5.7
  #   restart: always
  #   environment:
  #     MYSQL_DATABASE: 'db'
  #     # So you don't have to use root, but you can if you like
  #     MYSQL_USER: 'user'
  #     # You can use whatever password you like
  #     MYSQL_PASSWORD: 'password'
  #     # Password for root access
  #     MYSQL_ROOT_PASSWORD: 'password'
  #   ports:
  #     # <Port exposed> : < MySQL Port running inside container>
  #     - '3306:3306'
  #   expose:
  #     # Opens port 3306 on the container
  #     - '3306'
  #     # Where our data will be persisted
  #   volumes:
  #     - my-db:/var/lib/mysql
  server-app:
    restart: unless-stopped
    container_name: vcx-enterprise-server
    hostname: server-app
    restart: always
    build:
      context: .
    volumes: 
    #volumes may not work in remote deployment due to persmissions issues
      - ./data:/root/data
      - ./web:/root/web
    ports:
      - "8080:80"
    env_file:
      - ./config/env-enterprise-server.dev
    # depends_on:
    #   - db
    networks:
      - vcx_network
  wallet-app:
    restart: unless-stopped
    container_name: vcx-cloud-wallet
    hostname: wallet-app
    restart: always
    build:
      context: .
    volumes: 
    # volumes may not work in remote deployment due to persmissions issues
      - ./data:/root/data
      - ./web:/root/web
    ports:
      - "8081:80"
    env_file:
      - ./config/env-cloud-wallet.dev
    # depends_on:
    #   - db
    networks:
      - vcx_network
networks:
  vcx_network:
volumes:
  server:
  # my-db:
